#!/usr/bin/env python3
"""Generate a Markdown snapshot of the repository respecting .gitignore.

File contents are sanitized to avoid leaking Markdown formatting symbols into the
output, preserving a readable structure even if source files contain Markdown
syntax characters.
"""
from __future__ import annotations

import subprocess
from datetime import datetime
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent
OUTPUT_FILENAME = "project_snapshot.md"
OUTPUT_PATH = ROOT / OUTPUT_FILENAME

SANITIZE_MAP = {
    "#": "//",  # avoid accidental headings
    "*": "•",   # avoid bullet/italic markers
    "_": "‗",   # avoid italic/underline markers
    "`": "´",   # avoid inline/fenced code delimiters
    ">": "›",   # avoid blockquote markers
    "~": "≈",   # avoid strikethrough markers
}


def list_project_files() -> list[str]:
    """Return project files respecting .gitignore via git ls-files."""
    result = subprocess.run(
        ["git", "ls-files", "--exclude-standard", "--cached", "--others"],
        check=True,
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def read_file_content(path: Path) -> str:
    """Read a file as text, replacing undecodable bytes."""
    data = path.read_bytes()
    return data.decode("utf-8", errors="replace")


def format_section(path: Path, content: str) -> list[str]:
    """Format a single file section for the snapshot."""
    relative_path = path.relative_to(ROOT)
    return [
        f"## {relative_path}",
        "",
        "```",
        content,
        "```",
        "",
    ]


def sanitize_markdown_content(content: str) -> str:
    """Replace Markdown formatting symbols with harmless alternatives."""

    def replace_char(char: str) -> str:
        return SANITIZE_MAP.get(char, char)

    return "".join(replace_char(char) for char in content)


def build_snapshot(file_paths: Iterable[str]) -> str:
    """Build the complete Markdown snapshot as a string."""
    lines: list[str] = [
        "# Project Snapshot",
        "",
        f"Generated by `{Path(__file__).name}` on {datetime.utcnow().isoformat()}Z.",
        "Files are gathered using `git ls-files` with standard exclusions (respects `.gitignore`).",
        "",
    ]

    for relative_path_str in sorted(file_paths):
        path = ROOT / relative_path_str
        if path == OUTPUT_PATH:
            continue
        raw_content = read_file_content(path)
        sanitized_content = sanitize_markdown_content(raw_content)
        lines.extend(format_section(path, sanitized_content))

    return "\n".join(lines).rstrip() + "\n"


def write_snapshot(snapshot: str) -> None:
    OUTPUT_PATH.write_text(snapshot, encoding="utf-8")


def main() -> None:
    file_paths = list_project_files()
    snapshot = build_snapshot(file_paths)
    write_snapshot(snapshot)
    print(f"Snapshot written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
